# Generated by Django 5.1.3 on 2024-11-09 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anushka', '0004_furnitureandtoys'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing2d3d',
            name='link',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
