# Generated by Django 5.1.3 on 2024-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anushka', '0007_rename_image_drawing2d3d_image1_drawing2d3d_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnccutting',
            name='link',
        ),
        migrations.RemoveField(
            model_name='furnitureandtoys',
            name='link',
        ),
        migrations.RemoveField(
            model_name='lasercutting',
            name='link',
        ),
        migrations.RemoveField(
            model_name='metalstrture',
            name='link',
        ),
        migrations.RemoveField(
            model_name='printing3d',
            name='link',
        ),
        migrations.RemoveField(
            model_name='productrendering',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sheetmetal',
            name='link',
        ),
        migrations.AlterField(
            model_name='drawing2d3d',
            name='caption',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='furnitureandtoys',
            name='image',
            field=models.ImageField(upload_to='img_profiles'),
        ),
    ]
