# Generated by Django 5.1.3 on 2024-11-12 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anushka', '0009_rename_image_furnitureandtoys_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printing3d',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='printing3d',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='img_profiles'),
        ),
        migrations.AddField(
            model_name='printing3d',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='img_profiles'),
        ),
        migrations.AddField(
            model_name='printing3d',
            name='link',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
