# Generated by Django 5.1.3 on 2024-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anushka', '0010_rename_image_printing3d_image1_printing3d_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureandtoys',
            name='caption',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='printing3d',
            name='caption',
            field=models.CharField(max_length=70),
        ),
    ]
